apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: attendance-control-messages-handler
  name: attendance-control-messages-handler-deployment
  namespace: {_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-control-messages-handler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: attendance-control-messages-handler
        namespace: {_NAMESPACE}
    spec:
      containers:
        - name: attendance-control-messages-handler-container
          image: {_IMAGE}
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - -c
            - "npm run handle-messages"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
            
