version: '3.9'

services:
  postgres_db:
    image: postgres:16.3-alpine3.20
    container_name: local_pgdb
    restart: always
    ports:
      - ${DB_FORWARD_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-123456}
      - POSTGRES_DB=${DB_DATABASE:-leave_management_system}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - leave_management_system

  backend:
    container_name: leave-management-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_FORWARD_PORT:-8080}:${APP_PORT:-8080}
    volumes:
      - .:/app 
    networks:
      - leave_management_system
    restart: on-failure
    tty: true
    stdin_open: true
    expose:
      - ${APP_PORT:-8080}

networks:
  leave_management_system:
    name: 'leaves-management-shared-network'
    external: true 
  
volumes:
  pg_data: {}